### ISSUE TITLE
建议点歌姬在比较黑名单条目的时候，比较方法更改一下

### ISSUE THREAD

**Issue by Executor-Cheng** [Bililive/DMPlugin_DGJ#2]
https://github.com/Bililive/DMPlugin_DGJ/blob/1259ede1601a358ae78d18d97061614142ef9087/DMPlugin_DGJ/Main/Center.cs#L125
建议改为
`if (i.SongName.IndexOf(b.BLK_Text, StringComparison.CurrentCultureIgnoreCase) > -1)`
https://github.com/Bililive/DMPlugin_DGJ/blob/1259ede1601a358ae78d18d97061614142ef9087/DMPlugin_DGJ/Main/Center.cs#L129
建议改为
`if (i.SingersText.IndexOf(b.BLK_Text, StringComparison.CurrentCultureIgnoreCase) > -1)`
以忽略其大小写进行比较

**Comment by Genteure** [comment]
_(:3」∠)_ 还有啥别的有必要改的东西可以一起康康，大的小的都可以。反正再发打算版本号改到 3.0，breaking change 也是可以的（比如我打算把配置文件重写成json）。

**Comment by Executor-Cheng** [comment]
那等我通读一遍再看看

**Comment by Genteure** [comment]
fixed
