### ISSUE TITLE
建议加入歌单的导入和空闲时播放功能

### ISSUE THREAD

**Issue by hxdnshx** [Bililive/DMPlugin_DGJ#3]
尽管在当前的点歌姬版本中，包含了在空闲时使用系统播放器的功能，但是实际上在一部分情况下，这个功能无法与系统当前播放器正常交互；并且在调用系统播放器的情况下，就没有对应的歌词显示了。
对于之前使用系统播放器的功能，我是这样理解它的需求的：
1.在空闲时自动播放特定的一组音乐。
2.提供对虾米/网易云等平台上不存在的音乐提供播放功能。

对于这样的需求，我构想出的解决方案是这样的：
1.提供一个功能，当当前点歌列表<N时，从指定的播放列表（从网易云/虾米等搜索源获取播放列表）中选择出若干首曲目填充进当前的点歌列表。
2.提供一个内置搜索源，将本地的”音乐“目录作为一个搜索源，获取相应曲目（实测file://可以作为一个有效的地址）

不知您对于这方面的看法如何？

PS1：目前解决方案1已经通过外部插件的形式实现了，不知道合并进本体是不是更好的选择。

**Comment by hxdnshx** [comment]
目前对于1. 的想法，倾向于在搜索接口上再加一个播放列表的获取接口。来进行不分差别的playlist获取，并且在播放结束的时候进行曲目的插入。

**Comment by hxdnshx** [comment]
另外，对于您项目中的nuget包的依赖，您是什么看法。因为这会导致最终发布时有多于一个dll文件（不过似乎也可以通过ILMerge进行合并）

**Comment by Genteure** [comment]
nuget 依赖，目前是直接把 dll 文件作为资源文件打包进主 dll 里，然后在运行时释放到硬盘调用 `Assambly.LoadFrom()`，也算是实现了一个文件。

MaterialDesign 有点想去掉，不过还没想好具体怎么做。偶尔有人会遇到整个界面变成白屏（纯白色）的情况，不知道为什么。
NAudio 不知道怎么处理好。其他插件也有在使用 NAudio 的所以需要考虑一下会不会冲突。

Newtonsoft.Json 因为弹幕姬本身在用，所以不需要单独加载。

关于可能有冲突的问题，一个工作量会有点大但是效果会比较好的方案是使用 AppDomain 进行隔离。不过没啥冲突可能性的话不用也没啥关系。

**Comment by hxdnshx** [comment]
嗯，这是一个不错的解决方案。
在对于本地文件的检索，读取ID3条目和建立文件的索引过程，我觉得使用外部的nuget依赖可能是一个更好的方案，听了您的说明，似乎只要我做好模块的隔离，以及dll的打包，就可以啦。（本想写在internal里的，还是分出来作为单独的项目吧w）

**Comment by Genteure** [comment]
因为本项目弃用，所以 close
没有解决完的问题（本地歌曲搜索模块）转到 https://github.com/Bililive/DGJv3 继续
